server:
  port: 80
  servlet:
    context-path: /community

community:
  path:
    domain: http://localhost
  login-expired-seconds:
    default: 3600
    remember: 8640000
  upload-path: D:/IDEA/IDEA/IDEAProjects/HeartfeltWishesCommunity/header_image/

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC
      username: root
      password: lze010703
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
  mail:
    host: smtp.163.com
    port:
    username: l15997281839@163.com
    password: CSZSLJLJSMKBTCTC
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  redis:
    database: 1
    host: localhost
    port: 6379
  data:
    elasticsearch:
      cluster-name: community
      cluster-nodes: 127.0.0.1:9300
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    cache-enabled: false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true